#!/usr/bin/env bash
# Run on the server once after 'docker compose up -d', when the ipsec container
# first becomes healthy. Applies two persistent IKEv2 reconnection fixes:
#
#   1. uniqueids=replace  — Libreswan's default (set by hwdsl2) is uniqueids=no,
#      which lets reconnecting clients create a new IKE SA alongside the stale one.
#      The IP pool then has a conflict (same address held by two SAs) and the new
#      connection is rejected. 'replace' atomically swaps the old SA out, so the
#      reconnecting client gets the same IP without any conflict.
#
#   2. Aggressive DPD — the hwdsl2 default is dpddelay=30 with no explicit timeout,
#      meaning a stale SA can persist for 2-3 minutes after a client drops.
#      Reconnection attempts during that window hit the uniqueids conflict above.
#      Reducing to dpddelay=15 / dpdtimeout=60 cuts the window to ~75 seconds.
#
# Both fixes live in ./ipsec/data/ (bind-mounted as /etc/ipsec.d/ inside the
# container), so they survive container restarts:
#   - 00-reconnect-fix.conf  — 'config setup { uniqueids=replace }', merged by
#     Libreswan with the main /etc/ipsec.conf on every container start.
#   - ikev2.conf             — regenerated by hwdsl2 only on first run (when the
#     PKI is absent), so patching it once is sufficient.
#
# Re-running this script is safe — it skips patches already applied.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
DATA_DIR="$SCRIPT_DIR/ipsec/data"
cd "$SCRIPT_DIR"

[[ -f ".env" ]] || { echo "ERROR: .env not found — run generate-secrets.sh first"; exit 1; }
command -v docker >/dev/null 2>&1 || { echo "ERROR: docker is not installed"; exit 1; }

# ── Wait for healthy ────────────────────────────────────────────────────────

echo "Waiting for ipsec container to become healthy (up to 90s on first run)..."
for i in $(seq 1 30); do
    CONTAINER_ID=$(docker compose ps -q ipsec 2>/dev/null | head -1 || true)
    if [[ -n "$CONTAINER_ID" ]]; then
        STATUS=$(docker inspect --format='{{.State.Health.Status}}' "$CONTAINER_ID" 2>/dev/null || echo "")
        if [[ "$STATUS" == "healthy" ]]; then
            echo "ipsec container is healthy."
            break
        fi
    else
        STATUS="not running"
    fi
    if [[ $i -eq 30 ]]; then
        echo "ERROR: ipsec container did not become healthy after 150s."
        echo "  docker compose logs ipsec"
        exit 1
    fi
    echo "  ($i/30) status='${STATUS:-starting}', retrying in 5s..."
    sleep 5
done

# ── Fix 1: uniqueids=replace ────────────────────────────────────────────────

# Libreswan includes all /etc/ipsec.d/*.conf files at the end of /etc/ipsec.conf.
# A 'config setup' section in an included file is merged with the main one;
# later values override earlier ones. '00-' prefix places this file before
# ikev2.conf so it runs right after the main file's 'config setup uniqueids=no'.
OVERRIDE_CONF="$DATA_DIR/00-reconnect-fix.conf"
if [[ -f "$OVERRIDE_CONF" ]]; then
    echo "00-reconnect-fix.conf already present, skipping."
else
    cat > "$OVERRIDE_CONF" << 'EOF'
# Managed by setup-ipsec.sh — do not edit manually.
# Overrides the hwdsl2 default of uniqueids=no.  With 'no', a reconnecting
# client creates a second SA alongside the stale one, causing an IP-pool
# conflict that blocks the new connection.  'replace' atomically swaps the
# stale SA out so the reconnecting client always gets a clean slot.
config setup
    uniqueids=replace
EOF
    echo "Created $OVERRIDE_CONF (uniqueids=replace)"
fi

# ── Fix 2: aggressive DPD in ikev2.conf ────────────────────────────────────

IKEV2_CONF="$DATA_DIR/ikev2.conf"
if [[ ! -f "$IKEV2_CONF" ]]; then
    echo "ERROR: $IKEV2_CONF not found."
    echo "The ipsec container generates this file on first run."
    echo "Ensure the container completed PKI initialisation, then retry."
    exit 1
fi

if grep -q 'dpdtimeout' "$IKEV2_CONF"; then
    echo "$IKEV2_CONF already patched (dpdtimeout present), skipping."
else
    # Reduce probe interval from 30 s to 15 s and add an explicit 60 s timeout.
    # hwdsl2 generates 'dpddelay=30' with two-space indentation.
    sed -i -E 's/^[[:space:]]*dpddelay=[0-9]+/  dpddelay=15/' "$IKEV2_CONF"
    sed -i '/dpddelay=15/a\  dpdtimeout=60' "$IKEV2_CONF"
    echo "Patched $IKEV2_CONF (dpddelay=15, dpdtimeout=60)"
fi

# ── Restart to apply ────────────────────────────────────────────────────────

echo "Restarting ipsec container to load new configuration..."
docker compose restart ipsec

echo ""
echo "IKEv2 reconnection fixes applied."
echo ""
echo "Verify:"
echo "  docker compose exec ipsec grep uniqueids /etc/ipsec.conf"
echo "  docker compose exec ipsec ipsec status | grep ikev2-cp"
