server {
    listen 80;
    server_name universal.ramilkarimov.me;

    location / {
        auth_basic "VPN";
        auth_basic_user_file /etc/nginx/htpasswd-vpn;
        root /var/www/vpn;
        index index.html;
    }
}
